<a href="https://colab.research.google.com/github/ThreeOne31/CNN_Bird_Species_Classification/blob/master/Metric_Distance_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/ThreeOne31/knn_Metric_distance_learning.git

Cloning into 'knn_Metric_distance_learning'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.


In [2]:
import os
import math
import random
import operator

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

#change the working dir
os.chdir('knn_Metric_distance_learning/HTRU2')

#load data
pulsars_dataframe = pd.read_csv('HTRU_2.csv')
pulsars_dataframe.head()

140.5625  55.68378214  -0.234571412  -0.699648398  3.199832776  \
0  102.507812    58.882430      0.465318     -0.515088     1.677258   
1  103.015625    39.341649      0.323328      1.051164     3.121237   
2  136.750000    57.178449     -0.068415     -0.636238     3.642977   
3   88.726562    40.672225      0.600866      1.123492     1.178930   
4   93.570312    46.698114      0.531905      0.416721     1.636288   

   19.11042633  7.975531794  74.24222492  0  
0    14.860146    10.576487   127.393580  0  
1    21.744669     7.735822    63.171909  0  
2    20.959280     6.896499    53.593661  0  
3    11.468720    14.269573   252.567306  0  
4    14.545074    10.621748   131.394004  0

In [0]:
pulsars_dataframe.describe().transpose()

count        mean         std        min         25%  \
140.5625      17897.0  111.078321   25.652705   5.812500  100.929688   
55.68378214   17897.0   46.549021    6.843040  24.772042   42.375426   
-0.234571412  17897.0    0.477897    1.064056  -1.876011    0.027108   
-0.699648398  17897.0    1.770417    6.168058  -1.791886   -0.188528   
3.199832776   17897.0   12.614926   29.473637   0.213211    1.923077   
19.11042633   17897.0   26.326918   19.471042   7.370432   14.437330   
7.975531794   17897.0    8.303574    4.506217  -3.139270    5.781485   
74.24222492   17897.0  104.859419  106.517270  -1.976976   34.957119   
0             17897.0    0.091580    0.288440   0.000000    0.000000   

                     50%         75%          max  
140.5625      115.078125  127.085938   192.617188  
55.68378214    46.946435   51.022887    98.778911  
-0.234571412    0.223241    0.473349     8.069522  
-0.699648398    0.198736    0.928206    68.101622  
3.199832776     2.801839    5.464883   223.392140  
19.11042633    18.459977   28.428152   110.642211  
7.975531794     8.433872   10.702973    34.539844  
74.24222492    83.068996  139.310905  1191.000837  
0               0.000000    0.000000     1.000000

In [0]:
pulsars_dataframe.dtypes

140.5625        float64
55.68378214     float64
-0.234571412    float64
-0.699648398    float64
3.199832776     float64
19.11042633     float64
7.975531794     float64
74.24222492     float64
0                 int64
dtype: object

In [0]:
colnames_numeric = pulsars_dataframe.columns[0:8]
#Scaling a data in always a good idea while using KNN
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
pulsars_dataframe[colnames_numeric] = scaler.fit_transform(pulsars_dataframe[colnames_numeric] )

In [0]:
pulsars_dataframe.head()
#print(pulsars_dataframe[18])

140.5625  55.68378214  -0.234571412  -0.699648398  3.199832776  \
0  0.517628     0.460908      0.235415      0.018268     0.006560   
1  0.520346     0.196868      0.221138      0.040677     0.013030   
2  0.700933     0.437884      0.181750      0.016534     0.015368   
3  0.443854     0.214847      0.249044      0.041712     0.004327   
4  0.469784     0.296271      0.242110      0.031600     0.006376   

   19.11042633  7.975531794  74.24222492  0  
0     0.072524     0.364015     0.108443  0  
1     0.139188     0.288624     0.054610  0  
2     0.131583     0.266348     0.046581  0  
3     0.039684     0.462029     0.213369  0  
4     0.069473     0.365216     0.111797  0

In [0]:
#convert pandas dataframe to list
pulsars_list = pulsars_dataframe.values.tolist()
#convert pandas dataframe to a numpy array
pulsar_arr = pulsars_dataframe.to_numpy()

Add a new learning distance metric 






In [9]:
#print(pulsars_list[0:4])
#print(pulsars_list[4][0])
#print(pulsars_list[:,8])
#print(pulsars_list[8:9][-1])

X = pulsar_arr[:,0:8]
Y = pulsar_arr[:,8:9]
Y_trans = Y.transpose()
X_trans = X.transpose()
lamda = 0.3
print(X_trans)
print(Y_trans)

K_d= Y_trans.dot(Y) + lamda
print(Y.shape)
print(Y_trans.shape)
print(K_d)

#def MetricDistance(testInstance, trainingSet[x]):

[[0.51762787 0.52034628 0.70093263 ... 0.60771193 0.58186609 0.27435072]
 [0.46090841 0.19686832 0.43788377 ... 0.4751437  0.39361695 0.82458965]
 [0.23541516 0.22113842 0.18174959 ... 0.2046521  0.20885482 0.33003783]
 ...
 [0.0725243  0.13918843 0.13158337 ... 0.49869934 0.05820853 0.5552546 ]
 [0.36401483 0.28862387 0.26634832 ... 0.14965285 0.34892638 0.04091771]
 [0.10844339 0.05461031 0.04658145 ... 0.00550903 0.11418141 0.00285542]]
[[0. 0. 0. ... 0. 0. 0.]]
(17897, 1)
(1, 17897)
[[1639.3]]


In [0]:
#Breaking the data into training and test set
def train_test_split(data, split, trainingSet = [], testSet = []):
    for x in range(len(data)):
        if random.random() < split:
            trainingSet.append(data[x])
        else:
            testSet.append(data[x])
            
#defibe Euclian distance
def Euclideandist(x,xi, length):
    d = 0.0
    for i in range(length):
        d += pow(float(x[i])- float(xi[i]),2)
    return math.sqrt(d)

#Getting the K neighbours having the closest Euclidean distance to the test instance
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = Euclideandist(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors
  
#After sorting the neighbours based on their respective classes, max voting to give the final class of the test instance
def getResponse(neighbors):
	classVotes = {}
	for x in range(len(neighbors)):
		response = neighbors[x][-1]
		if response in classVotes:
			classVotes[response] += 1
		else:
			classVotes[response] = 1
	sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)#Sorting it based on votes
	return sortedVotes[0][0] #Please note we need the class for the top voted class, hence [0][0]#


#Getting the accuracy
def getAccuracy(testSet, predictions):
	correct = 0
	for x in range(len(testSet)):
		if testSet[x][-1] == predictions[x]:
			correct += 1
	return (correct/float(len(testSet))) * 100.0

In [0]:
trainingSet = []
testSet = []
split = 0.66
train_test_split(pulsars_list, split, trainingSet, testSet)


# generate predictions
predictions=[]
k = 3
for x in range(len(testSet)):
    neighbors = getNeighbors(trainingSet, testSet[x], k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(testSet[x][-1]))

In [7]:
accuracy = getAccuracy(testSet, predictions)
print('Accuracy: ' + repr(accuracy) + '%')

Accuracy: 97.83363651397387%
